WebMvc/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dao;
using WebSanatorium.Api;
using WebSanatorium.Db;

namespace WebMvc.Controllers
{
    public class DoctorsController : Controller
    {
        private DbConnection db = DbConnectionProvider.GetConnection();

        // GET: Doctors
        public ActionResult Index()
        {
            return View(db.Doctors.ToList());
        }

        // GET: Doctors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // GET: Doctors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Doctors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FullName,Photo")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Doctors.Add(doctor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(doctor);
        }

        // GET: Doctors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            ViewBag.Specialties = db.Specialties.AsEnumerable();

            return View(doctor);
        }

        // POST: Doctors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FullName, Old, Photo")] Doctor doctor, HttpPostedFileBase upload)
        {
            if (upload != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(upload.FileName);

                // сохраняем файл в папку Files в проекте
                upload.SaveAs(Server.MapPath("~/Content/DoctorImgs/" + fileName));

                doctor.Photo = fileName;
            }

            if (ModelState.IsValid)
            {
                var d = db.Doctors.Find(doctor.Id);
                d.FullName = doctor.FullName;
                d.Old = doctor.Old;
                d.Photo = doctor.Photo;
                
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(doctor);
        }

        // GET: Doctors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Doctor doctor = db.Doctors.Find(id);
            db.Doctors.Remove(doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        /// <summary>
        /// http://metanit.com/sharp/articles/26.php
        /// Загрузка фотографии комнаты на сервер
        /// </summary>
        /// <param name="upload"></param>
        /// <param name="doctor"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase upload, Doctor doctor)
        {
            var reqest = Request;

            if (upload != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(upload.FileName);
                
                // сохраняем файл в папку Files в проекте
                upload.SaveAs(Server.MapPath("~/Content/DoctorImgs/" + fileName));

                doctor.Photo = fileName;
            }

            return View("Edit", doctor);
        }

       
    }
}

WebMvc/Views/Doctors/Create.cshtml
@using WebMvc.Views
@model WebSanatorium.Api.Doctor

@{
    ViewBag.Title = "Добавление сотрудника";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.FullName, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Old, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Old, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Old, "", new { @class = "text-danger" })
            </div>
        </div>


        @*<div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @using (Html.BeginForm("Upload", "Doctors", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <table>
                        <tr>
                            <td>Для загрузки фотографии &nbsp;</td>
                            <td><input type="file" name="upload" /></td>
                            <td>и нажмите кнопку &nbsp; <input type="submit" value="Загрузить" /></td>
                        </tr>
                        <tr>
                            <td>
                                @{ var file = "/Context/DoctorImgs/" + Model.Photo; }
                                <span><img src=@file width="200" />&nbsp;&nbsp;</span>
                            </td>
                        </tr>
                    </table>
                                    }
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@Str.Create class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(Str.ToList, "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebMvc/Views/Doctors/Delete.cshtml
@using WebMvc.Views
@model WebSanatorium.Api.Doctor

@{
    ViewBag.Title = "Удаление сотрудника";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>@ViewBag.Title</h2>

<h3>Уверены, что хотите удалить сотрудника?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value=@Str.Delete class="btn btn-default" /> |
            @Html.ActionLink(Str.ToList, "Index")
        </div>
    }
</div>

WebMvc/Views/Doctors/Details.cshtml
@using WebMvc.Views
@model WebSanatorium.Api.Doctor

@{
    ViewBag.Title = "Детальная информация о сотруднике";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>@ViewBag.Title</h2>


<div>
    <hr />
    <table width="100%">
        <tr >
            <td width="50%" valign="top">

                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.FullName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.FullName)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Old)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Old)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Specialties)
                    </dt>
                    <dd>
                        @Html.ListBox("Id", Model.Specialties.Select(d => new SelectListItem()
                        {
                            Text = d.Name,
                            Value = d.Id.ToString()
                        }).AsEnumerable())
                    </dd>
                </dl>
            </td>
            <td>
                @{ var file = "/Content/DoctorImgs/" + Model.Photo; }
                <span><img src="@file" width="200" />&nbsp;&nbsp;</span>
            </td>
        </tr>
    </table>
</div>



<p>
    @Html.ActionLink(Str.Edit, "Edit", new { id = Model.Id }) |
    @Html.ActionLink(Str.ToList, "Index")
</p>

WebMvc/Views/Doctors/Edit.cshtml
@using WebMvc.Views
@using WebSanatorium.Api
@model WebSanatorium.Api.Doctor

@{
    ViewBag.Title = "Изменений данных о сотруднике";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>@ViewBag.Title</h2>



@using (Html.BeginForm("Edit", "Doctors", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Photo)
    <table width ="100%">
            <tr>
                <td width="50%">
                    <table width="100%">
                        <tr>
                            <td width="50%">
                                @Html.LabelFor(model => model.FullName, htmlAttributes: new {@class = "control-label col-md-2"})
                            </td>
                            <td>
                                @Html.EditorFor(model => model.FullName, new {htmlAttributes = new {@class = "form-control"}})
                                @Html.ValidationMessageFor(model => model.FullName, "", new {@class = "text-danger"})
                            </td>
                        </tr>
                        <tr>
                            <td width="50%">
                                @Html.LabelFor(model => model.Old, htmlAttributes: new {@class = "control-label col-md-2"})
                            </td>
                            <td>
                                @Html.EditorFor(model => model.Old, new {htmlAttributes = new {@class = "form-control"}})
                                @Html.ValidationMessageFor(model => model.Old, "", new {@class = "text-danger"})
                            </td>
                        </tr>
                        <tr>
                            <td width="50%">
                                @Html.LabelFor(model => model.Specialties, htmlAttributes: new { @class = "control-label col-md-2" })
                            </td>
                            <td>
                                @{ //Подготовка списка для ListBox
                                    var specialties = ((IEnumerable<Specialty>)ViewBag.Specialties).Select(x => new SelectListItem
                                    {
                                        Text = x.Name,
                                        Value = x.Id.ToString()
                                    }).AsEnumerable();
                                }
                                @Html.ListBoxFor(model => model.Specialties, specialties , new {htmlAttributes = new {@class = "form-control"}})
                            </td>
                        </tr>
                        <tr>
                            <td width="50%">
                                @Html.LabelFor(model => model.Photo, htmlAttributes: new {@class = "control-label col-md-2"})
                            </td>
                            <td>
                                <input type="file" name="upload"/>
                            </td>
                        </tr>
                        <tr>
                            <td width="50%">
                            </td>
                            <td>
                                <input type="submit" value=@Str.Save class="btn btn-default" />
                            </td>
                        </tr>
                      </table>
                </td>
                <td>
                    @{ var file = "/Content/DoctorImgs/" + Model.Photo; }
                    <span><img src="@file" width="200" />&nbsp;&nbsp;</span>
                </td>
            </tr>
        </table>
  
}

<div>
    @Html.ActionLink(Str.ToList, "Index")
</div>

@*@section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@

WebMvc/Views/Doctors/Index.cshtml
@using WebMvc.Views
@model IEnumerable<WebSanatorium.Api.Doctor>

@{
    ViewBag.Title = "Сотрудники";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>@ViewBag.Title</h2>
<hr />

<p>
    @Html.ActionLink(Str.Create, "Create")
</p>

<table class="table">
@foreach (var item in Model) {
    <tr>
        <td>
            @{ var file = "/Content/DoctorImgs/" + item.Photo; }
            <span><img src="@file" width="70" />&nbsp;&nbsp;</span>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FullName)
        </td>

        <td>
            @Html.ActionLink(Str.Edit, "Edit", new {id = item.Id}) |
            @Html.ActionLink(Str.Details, "Details", new {id = item.Id}) |
            @Html.ActionLink(Str.Delete, "Delete", new {id = item.Id})
        </td>
    </tr>
}

</table>