WebMvc/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dao;
using WebSanatorium.Api;
using WebSanatorium.Db;

namespace WebMvc.Controllers
{
    public class RoomsController : Controller
    {
        private DbConnection db = DbConnectionProvider.GetConnection();

        // GET: Rooms
        public ActionResult Index()
        {
            return View(db.Rooms.ToList());
        }

        // GET: Rooms/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        // GET: Rooms/Create
        public ActionResult Create()
        {
            ViewBag.RoomClassList = db.RoomClasses.AsEnumerable();

            return View();
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Number,PictureFile")] Room room, RoomClass roomClass, HttpPostedFileBase upload)
        {
            if (upload != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(upload.FileName);

                // сохраняем файл в папку Files в проекте
                upload.SaveAs(Server.MapPath("~/Content/RoomImgs/" + fileName));

                room.PictureFile = fileName;
            }

            if (ModelState.IsValid)
            {
                room.RoomClass = db.RoomClasses.Find(roomClass.Id);
                db.Rooms.Add(room);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(room);
        }

        // GET: Rooms/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }

            ViewBag.RoomClassList = db.RoomClasses.AsEnumerable();

            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Number,PictureFile")] Room room, RoomClass roomClass, HttpPostedFileBase upload)
        {
            if (upload != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(upload.FileName);

                // сохраняем файл в папку Files в проекте
                upload.SaveAs(Server.MapPath("~/Content/RoomImgs/" + fileName));

                room.PictureFile = fileName;
            }

            if (ModelState.IsValid)
            {
                var r = db.Rooms.Find(room.Id);
                r.Number = room.Number;
                r.PictureFile = room.PictureFile;
                r.RoomClass = db.RoomClasses.Find(roomClass.Id);

                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.RoomClassList = db.RoomClasses.AsEnumerable();

            return View(room);
        }

        // GET: Rooms/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Room room = db.Rooms.Find(id);
            db.Rooms.Remove(room);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        /// <summary>
        /// http://metanit.com/sharp/articles/26.php
        /// Загрузка фотографии комнаты на сервер
        /// </summary>
        /// <param name="upload"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase upload)
        {
            if (upload != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(upload.FileName);
                // сохраняем файл в папку Files в проекте
                upload.SaveAs(Server.MapPath("~/Content/RoomImgs/" + fileName));
                
                //Room room = db.Rooms.Find(id);

                //room.PictureFile = fileName;

                //db.SaveChanges();
            }
            TempData["id"] = 1;

            return Redirect("Edit");
        }

       
    }
}

WebMvc/Views/Rooms/Create.cshtml
@using WebMvc.Views
@using WebSanatorium.Api
@model WebSanatorium.Api.Room

@{
    ViewBag.Title = "Добавление номера";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "Rooms", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoomClass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @{ //Подготовка списка для dropdown
                        var classList = ((IEnumerable<RoomClass>)ViewBag.RoomClassList).Select(x => new SelectListItem
                        {
                            Text = x.Name,
                            Value = x.Id.ToString()
                        }).AsEnumerable();
                    }
               
                    @Html.DropDownListFor(m => m.RoomClass.Id, classList, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(m => m.RoomClass.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PictureFile, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                <input type="file" name="upload"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@Str.Create  class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(Str.ToList, "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebMvc/Views/Rooms/Delete.cshtml
@using WebMvc.Views
@model WebSanatorium.Api.Room

@{
    ViewBag.Title = "Удаление номера";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>@ViewBag.Title</h2>

<h3>Действительно хотите удалить номер?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PictureFile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PictureFile)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value=@Str.Delete  class="btn btn-default" /> |
            @Html.ActionLink(Str.ToList, "Index")
        </div>
    }
</div>

WebMvc/Views/Rooms/Details.cshtml
@using WebMvc.Views
@model WebSanatorium.Api.Room

@{
    ViewBag.Title = "Детальная информация о номере";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>@ViewBag.Title</h2>
<div>
    <hr />
    <table width="100%">
        <tr>
            <td width="50%" valign="top">

                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Number)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Number)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.RoomClass)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.RoomClass.Name)
                    </dd>

                </dl>
            </td>
            <td>
                @{ var file = "/Content/RoomImgs/" + Model.PictureFile; }
                <span><img src="@file" width="800" />&nbsp;&nbsp;</span>
            </td>
        </tr>
    </table>
</div>
<p>
    @Html.ActionLink(Str.Edit, "Edit", new { id = Model.Id }) |
    @Html.ActionLink(Str.ToList, "Index")
</p>

WebMvc/Views/Rooms/Edit.cshtml
@using WebMvc.Views
@using WebSanatorium.Api
@model WebSanatorium.Api.Room

@{
    ViewBag.Title = "Редактирование номера";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Edit", "Rooms", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.PictureFile)

    <table width="100%">
        <tr>
            <td width="50%">
                <table width="100%">
                    <tr>
                        <td width="50%">
                            @Html.LabelFor(model => model.Number, htmlAttributes: new {@class = "control-label col-md-2"})
                        </td>
                        <td>
                            @Html.EditorFor(model => model.Number, new {htmlAttributes = new {@class = "form-control"}})
                            @Html.ValidationMessageFor(model => model.Number, "", new {@class = "text-danger"})
                        </td>
                    </tr>
                    <tr>
                        <td width="50%">
                            @Html.LabelFor(model => model.RoomClass, htmlAttributes: new { @class = "control-label col-md-2" })
                        </td>
                        
                            @{ //Подготовка списка для dropdown
                                var classList = ((IEnumerable<RoomClass>) ViewBag.RoomClassList).Select(x => new SelectListItem
                                {
                                    Text = x.Name,
                                    Value = x.Id.ToString()
                                }).AsEnumerable();
                        }
                        <td>
                            @Html.DropDownListFor(m=>m.RoomClass.Id, classList, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(m => m.RoomClass.Id, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                    <tr>
                        <td width="50%">
                            @Html.LabelFor(model => model.PictureFile, htmlAttributes: new {@class = "control-label col-md-2"})
                        </td>
                        <td>
                            <input type="file" name="upload"/>
                        </td>
                    </tr>
                    <tr>
                        <td width="50%"></td>
                        <td>
                            <input type="submit" value=@Str.Save class="btn btn-default"/>
                        </td>
                    </tr>
                </table>
            </td>
            <td>
                @{ var file = "/Content/RoomImgs/" + Model.PictureFile; }
                <span><img src="@file" width="400" />&nbsp;&nbsp;</span>
            </td>
        </tr>
    </table>
    </div>
}

<div>
    @Html.ActionLink(Str.ToList, "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebMvc/Views/Rooms/Index.cshtml
@using WebMvc.Views
@model IEnumerable<WebSanatorium.Api.Room>

@{
    ViewBag.Title = "Номера";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>@ViewBag.Title</h2>
<p>
    @Html.ActionLink(Str.Create, "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PictureFile)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoomClass.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Number)
        </td>
        <td>
            @{ var file = "/Content/RoomImgs/" + item.PictureFile; }
            <span><img src="@file" width="70" />&nbsp;&nbsp;</span>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoomClass.Name)
        </td>
        <td>
            @Html.ActionLink(Str.Edit, "Edit", new { id = item.Id }) |
            @Html.ActionLink(Str.Details, "Details", new { id = item.Id }) |
            @Html.ActionLink(Str.Delete, "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>